### ISSUE TITLE
[Some error in profiling]The process's error and profiling data's format error

### ISSUE THREAD

**Issue by qwz111** [Cloud-and-Distributed-Systems/Erms#11]
Hi, when I run
```bash
./AE/scripts/profiling-testing.sh
```
There are no errors in the previous part of the running output. However, at the end of this process, my terminal's output is:
```bash
Exception ignored in: <function Pool.__del__ at 0x7f151cb47130>
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 271, in __del__
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```
But I can see the output profiling data, namely `latencyByPod.csv` and `spanRelationships.csv`. But in `spanRelationships.csv`, my format of data is this:
```bash
parentMS,childMS,parentOperation,childOperation,tag,service
nginx,nginx,/wrk2-api/review/compose,/wrk2-api/review/compose,1,ComposeReview
nginx,nginx,/wrk2-api/review/compose,ComposeReview,1.1,ComposeReview
nginx,movie-id-service,ComposeReview,UploadMovieId,1.1.1,ComposeReview
movie-id-service,movie-id-service,UploadMovieId,MmcGetMovieId,1.1.1.1,ComposeReview
movie-id-service,movie-id-service,UploadMovieId,MmcSetMovieId,1.1.1.2,ComposeReview
movie-id-service,rating-service,UploadMovieId,UploadRating,1.1.1.3,ComposeReview
rating-service,rating-service,UploadRating,RedisInsert,1.1.1.3.1,ComposeReview
rating-service,compose-review-service,UploadRating,UploadRating,1.1.1.3.2,ComposeReview
movie-id-service,compose-review-service,UploadMovieId,UploadMovieId,1.1.1.4,ComposeReview
……
```
compared to your sample of `spanRelationships.csv`, **your output file containers extra column, namely step**. And this column is useful to the phase of online scaling. I search the root of this file, but **I can't find where to create the column, namely step**. So I want to know how I should inspect it.
Thank you vary much!

**Comment by Nick-LCY** [comment]
> However, at the end of this process, my terminal's output is:
> ```bash
> Exception ignored in: <function Pool.__del__ at 0x7f151cb47130>
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/multiprocessing/pool.py", line 271, in __del__
>   File "/usr/lib/python3.10/multiprocessing/queues.py", line 371, in put
> AttributeError: 'NoneType' object has no attribute 'dumps'

I think this is okay; it was probably caused by some data collection processes failing. You may have lost some data, but since you have several repeats in your profiling procedure, the other repeats should cover those lost parts.

> compared to your sample of spanRelationships.csv, your output file containers extra column, namely step. And this column is useful to the phase of online scaling.

Thank you for this good question. I forgot to mention how I generated this column and its meaning. I used `step` to distinguish between sequential and parallel invokes.

For all invokes that belong to the same parent, if they have the same `step`, they will be treated as **parallel invokes**; otherwise, they will be considered **sequential invokes**. Currently, I simply add them to the `spanRelationships.csv` by hand based on Jaeger's dependency graph. A simple example is provided below:

![Screenshot from Jaeger](https://github.com/user-attachments/assets/9c2a9eb4-cfc8-4964-8c35-bf1edb43038c)


I don't plan to add another script to generate `step`, since DeathStarBench always generates the same dependency graph. However, I will add this information to the README. Thank you again for your question.
