### ISSUE TITLE
[Profiling data not given]

### ISSUE THREAD

**Issue by QueJJ** [Cloud-and-Distributed-Systems/Erms#4]
Excuse me. I saw that you will provide the profiling data in `AE/data/data_{app}` for convenience. However, I did not see the folder. Could you please upload that folder? 

Thanks !

**Comment by caohch-1** [comment]
Can be found on [Zenodo](https://zenodo.org/record/7133267#.ZBAijdIzYUE). Not sure if it is the latest version.

**Comment by Nick-LCY** [comment]
It is important to note that this data can **ONLY** be used to generate theoretical results and not for practical experiments. When you deploy the benchmark in a different specification, you will need to re-profiling microservices.
