### ISSUE TITLE
Exception when running `AE/scripts/profiling-testing.sh`

### ISSUE THREAD

**Issue by SmartHypercube** [Cloud-and-Distributed-Systems/Erms#7]
We encountered an exception when running `AE/scripts/profiling-testing.sh` with the hotel application. Could you kindly advise us on the possible cause and potential solutions?
![exception-profiling-testing](https://github.com/Cloud-and-Distributed-Systems/Erms/assets/7789364/ed6ca0f6-003e-4bcc-908e-f052e00e7a2a)

**Comment by Nick-LCY** [comment]
Hi, could you please check the `log` folder and find log of your experiment? In that file, there will be something looks like:

> \<info\> \<2023/07/31 18:14:44\> Fetch CPU usage from: http://{prometheus_host}/api/v1/query_range?{...query...}

You can check that URL to see if it returns the data. If not, you can try updating PromQL as I mentioned in #6 and see if it works.
