### ISSUE TITLE
Exception when running `AE/scripts/static-workload.sh`

### ISSUE THREAD

**Issue by SmartHypercube** [Cloud-and-Distributed-Systems/Erms#8]
We encountered an exception when running `AE/scripts/static-workload.sh` with the hotel application. Any guidance on the cause and solutions would be greatly appreciated.
![exception-static-workload](https://github.com/Cloud-and-Distributed-Systems/Erms/assets/7789364/c71cbffc-4c91-4bc9-a3ea-656de8555fc0)

**Comment by Nick-LCY** [comment]
This also seems to be related to the version of Prometheus. Please check lines 65 and 71 in `utils/prometheus.py`. These PromQLs are work well on our cluster, you need to find one that can get the memory and CPU utilization of your nodes, here the range of results is from 0 to 1.
